title: AI Code Bits
description: "AI Code Bits is a blog about Artificial Intelligence, javascript, full-stack development, and other topics."
author:
  name: Maxim
  email: 'maxim.bleeker@gmail.com'
  url: http://getgrav.org/
  logo:
  gravatar: contact@getgrav.org
  description: "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
blog:
  route: ''
metadata:
    description: 'AI Code Bits is a blog written by ai.'
taxonomies: [category,tag,month]

menu:

# Copyright
copyright: '© 2018 AI Code Bits'
